## @file
# Azure Pipeline build file for a build using Windows and the Visual Studio compiler
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

trigger:
- dev/*
- release/202208
- release/202202

pr:
- dev/*
- release/202208
- release/202202

schedules:
- cron: "0 8 * * 0,3"   # Sun/Wed at 1AM Pacific
  displayName: Sun/Wed Build
  branches:
    include:
    - dev/*
    - release/202208
    - release/202202
  always: true          # Always build, even if no changes

jobs:
- template: Jobs/PrGate.yml@mu_devops
  parameters:
    arch_list: IA32,X64
    do_ci_build: true
    do_ci_setup: true
    do_non_ci_setup: true
    packages: OemPkg
    target_list: DEBUG,RELEASE,NO-TARGET,NOOPT
    tool_chain_tag: VS2022
    vm_image: windows-2022
